# Generated by Django 2.0.7 on 2018-08-25 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='seenby',
            field=models.ManyToManyField(blank=True, related_name='seen_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
