# Generated by Django 2.0.7 on 2018-08-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180823_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
