# Generated by Django 2.0.7 on 2018-08-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=250, null=True),
        ),
    ]
