# Generated by Django 2.0.4 on 2018-05-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=1450, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='translit_subject',
            field=models.CharField(blank=True, max_length=1250, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(blank=True, max_length=1250, null=True),
        ),
    ]
