# Generated by Django 2.0.4 on 2018-05-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180503_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='attached_image_path',
            field=models.CharField(blank=True, max_length=1450, null=True),
        ),
    ]
