# Generated by Django 2.0.4 on 2018-05-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ip_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ip_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
