# Generated by Django 2.0.4 on 2018-05-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180506_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_lastedited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
