# Generated by Django 2.0.4 on 2018-05-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_time_lastedited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time_lastedited',
            new_name='time_last_commented',
        ),
        migrations.AddField(
            model_name='post',
            name='time_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
