# Generated by Django 2.0.4 on 2018-05-02 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='haters',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='lovers',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='mehs',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='time_published',
        ),
    ]
