# Generated by Django 2.0.4 on 2018-05-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180501_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='time_published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
