# Generated by Django 2.0.4 on 2018-05-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_topic_time_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='translit_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
