# Generated by Django 2.0.4 on 2018-05-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20180502_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='ip_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='ip_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='ip_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
