# Generated by Django 2.0.4 on 2018-05-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_topic_translit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='subject_translit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
