# Generated by Django 2.0.4 on 2018-05-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20180506_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='time_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
