# Generated by Django 2.0.4 on 2018-05-02 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_emotion_subject_translit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotion',
            old_name='subject_translit',
            new_name='translit_subject',
        ),
    ]
