# Generated by Django 2.0.4 on 2018-04-26 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('username', models.CharField(blank=True, max_length=250, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('profile_image_path', models.CharField(blank=True, default='/media/avatars/default.png', max_length=250, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('is_new', models.NullBooleanField(default=True)),
                ('activation_sent', models.NullBooleanField(default=False)),
                ('is_activated', models.NullBooleanField(default=False)),
                ('is_avatar_processed', models.BooleanField(default=False)),
                ('is_avatar_transfered', models.BooleanField(default=False)),
                ('is_signature_customized', models.BooleanField(default=False)),
                ('is_notification_sent', models.NullBooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('is_confirmed', models.NullBooleanField(default=False)),
                ('is_cleared', models.BooleanField(default=False)),
                ('is_facebook_signup_used', models.BooleanField(default=False)),
                ('is_google_signup_used', models.BooleanField(default=False)),
                ('is_twitter_signup_used', models.BooleanField(default=False)),
                ('is_vk_signup_used', models.BooleanField(default=False)),
                ('is_linkedin_signup_used', models.BooleanField(default=False)),
                ('is_username_customized', models.BooleanField(default=False)),
                ('is_user_avatar', models.BooleanField(default=False)),
                ('is_google_avatar', models.BooleanField(default=False)),
                ('is_facebook_avatar', models.BooleanField(default=False)),
                ('is_twitter_avatar', models.BooleanField(default=False)),
                ('is_vk_avatar', models.BooleanField(default=False)),
                ('activation_key', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'verbose_name': 'Profile',
            },
        ),
    ]
