# Generated by Django 2.0.7 on 2018-08-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_color',
            field=models.CharField(blank=True, default='#000000', max_length=250, null=True),
        ),
    ]
