# Generated by Django 2.0.4 on 2018-05-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180511_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_new',
            field=models.BooleanField(default=False),
        ),
    ]
