"""
Django settings for lovehate project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import logging.config
from django.utils.log import DEFAULT_LOGGING
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Disable Django's logging setup
LOGGING_CONFIG = None

LOGLEVEL = os.environ.get('LOGLEVEL', 'info').upper()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b*2=^b67yesj%9!0c32=_oshfa-(l(n(8=r2zn!l7vsv5ble#='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

BASE_URL = 'https://lovehate.io'
ALLOWED_HOSTS = ['lovehate.io','www.lovehate.io','127.0.0.1','localhost','www.googleapis.com','https://www.googleapis.com']

SCOPES = ['https://www.googleapis.com/plus/v1/people/me',
          'https://www.googleapis.com/auth/plus.me',
          'https://www.googleapis.com/auth/plus.stream.write']
VERIFY_SSL = False

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'grappelli',
    'bootstrap3',
    'bootstrap',
    'bootstrap_toolkit',
    'bootstrapform_jinja',
    'clear_cache',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admin_tools',
    'django_filters',
    'django_redis',
    'django_jinja',
    'bootstrap_pagination',
    'oauth2_provider',
    'registration_api',
    'rest_framework',
    'rest_framework_jwt',
    'rest_framework_filters',
    'rest_framework.authtoken',
    'rest_auth',
    'rest_auth.registration',
    'social_core',
    #'allauth',
    #'allauth.account',
    #'allauth.socialaccount',
    'imagekit',
    'corsheaders',
    'online_users',
    'custom.blog',
    'custom.forum',
    'custom.users',
    'custom.gui',
    'custom.utils',
    'custom.meta',
]

GRAPPELLI_ADMIN_TITLE = str('Любовь и Ненависть')
GRAPPELLI_CLEAN_INPUT_TYPES = True

MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',    # This must be first on the li
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'online_users.middleware.OnlineNowMiddleware',
#    'django.middleware.cache.FetchFromCacheMiddleware', # This must be last
]

SESSION_IDLE_TIMEOUT = 1800
ROOT_URLCONF = 'lovehate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lovehate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'lovehatedb',
        'USER': 'root',
        'PASSWORD': 'Dracula2016',
        'HOST': 'localhost',
        'PORT': '',
    }

}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # default
    'custom.users.backends.LocalBackend',
#    "allauth.account.auth_backends.AuthenticationBackend",
#    'guardian.backends.ObjectPermissionBackend',
)

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static_files'),
                    os.path.join(BASE_DIR, 'static_files/js'),
                    os.path.join(BASE_DIR, 'static_files/html'),)
STATIC_ROOT = os.path.join(BASE_DIR, 'static', )
STATIC_URL = 'https://lovehate.io/static/'
REGISTRATION_API_ACTIVATION_SUCCESS_URL = '/'
ACTIVATION_HOST = ''
MEDIA_ROOT = './media/'
MEDIA_URL = '/media/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            'loaders': [
                'admin_tools.template_loaders.Loader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                'django_jinja.loaders.FileSystemLoader',
                'django_jinja.loaders.AppLoader',
            ],

            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

CORS_ORIGIN_ALLOW_ALL=True
REST_USE_JWT = True

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
#        'rest_framework.authentication.SessionAuthentication', 
   ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
 #       'rest_framework.permissions.IsAuthenticated',
    ]
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
        },
    },
   'django.security': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': False,
    },
    'root': {'level': 'INFO'},
}
from django.utils.translation import ugettext_lazy as _

LANGUAGES = [
    ('ru', _('Russian')),
    ('en', _('English')),
]


LANGUAGE_CODE = 'ru'
TIME_ZONE = 'EST'
ADMINISTRATOR_PASSWORD = 'nu45edi1'
ADMINISTRATOR_USERNAME = 'root'
USE_I18N = True
USE_L10N = True
USE_TZ = True
BITLY_API_TOKEN = 'cdb41a479f1be7644f161342b142390c360c4f5a'
GOOGLE_API_KEY = 'AIzaSyAQG2BHktxEvFZcvy2W-3rztJfYynyqm40'
REST_SESSION_LOGIN = True
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_FILE_PATH = '/tmp/email-messages'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'dmitryro'
EMAIL_HOST_PASSWORD = 'nu45edi1'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
TIME_ZONE = 'Europe/Moscow'


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "example"
    }
}

#SESSION_ENGINE = "django.contrib.sessions.backends.cache"

#Cookie name. this can be whatever you want
#SESSION_COOKIE_NAME='sessionid'  # use the sessionid in your views code
#the module to store sessions data
#SESSION_ENGINE='django.contrib.sessions.backends.db'    
#age of cookie in seconds (default: 2 weeks)
#SESSION_COOKIE_AGE= 24*60*60*7 # the number of seconds for only 7 for example
#whether a user's session cookie expires when the web browser is closed
#SESSION_EXPIRE_AT_BROWSER_CLOSE=False
#whether the session cookie should be secure (https:// only)
#SESSION_COOKIE_SECURE=False
#USER_LASTSEEN_TIMEOUT = 300
