"""
Django settings for lovehate project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b*2=^b67yesj%9!0c32=_oshfa-(l(n(8=r2zn!l7vsv5ble#='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

BASE_URL = 'https://lovehate.io'
ALLOWED_HOSTS = ['lovehate.io','www.lovehate.io','127.0.0.1','localhost','www.googleapis.com','https://www.googleapis.com']

SCOPES = ['https://www.googleapis.com/plus/v1/people/me',
          'https://www.googleapis.com/auth/plus.me',
          'https://www.googleapis.com/auth/plus.stream.write']
VERIFY_SSL = False

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'grappelli',
    'bootstrap3',
    'bootstrap',
    'bootstrap_toolkit',
    'bootstrap_pagination',
    'bootstrapform_jinja',
    'clear_cache',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admin_tools',
    'django_filters',
    'django_jinja',
    'oauth2_provider',
    'guardian',
    'registration_api',
    'rest_framework',
    'rest_framework_jwt',
    'rest_framework.authtoken',
    'rest_auth',
    'rest_auth.registration',
    'social_core',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'imagekit',
    'corsheaders',
    'custom.users',
    'custom.gui',
    'custom.utils',
    'custom.meta',
]

GRAPPELLI_ADMIN_TITLE = str('Любовь и Ненависть')
GRAPPELLI_CLEAN_INPUT_TYPES = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
 #   'custom.users.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'lovehate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lovehate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'lovehatedb',
        'USER': 'root',
        'PASSWORD': 'Dracula2016',
        'HOST': 'localhost',
        'PORT': '',
    }

}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators
AUTHENTICATION_BACKENDS = (
 #   'social_core.backends.open_id.OpenIdAuth',
 #   'social_core.backends.google.GoogleOpenId',
 #   'social_core.backends.google.GoogleOAuth2',
 #   'social_core.backends.google.GoogleOAuth',
 #   'social_core.backends.twitter.TwitterOAuth',
 #   'social_core.backends.facebook.FacebookOAuth2',
 #   'social_core.backends.facebook.FacebookAppOAuth2',
#    'social_core.backends.linkedin.LinkedinOAuth',
#    'social_core.backends.linkedin.LinkedinOAuth2',
#    'social.backends.instagram.InstagramOAuth2',
    'django.contrib.auth.backends.ModelBackend', # default
    "allauth.account.auth_backends.AuthenticationBackend",
#    'guardian.backends.ObjectPermissionBackend',
)

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static_files'),
                    os.path.join(BASE_DIR, 'static_files/js'),
                    os.path.join(BASE_DIR, 'static_files/html'),)
STATIC_ROOT = os.path.join(BASE_DIR, 'static', )
STATIC_URL = 'https://lovehate.io/static/'
REGISTRATION_API_ACTIVATION_SUCCESS_URL = '/'
ACTIVATION_HOST = ''
MEDIA_ROOT = './media/'
MEDIA_URL = '/media/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            'loaders': [
                'admin_tools.template_loaders.Loader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                'django_jinja.loaders.FileSystemLoader',
                'django_jinja.loaders.AppLoader',
            ],

            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

CORS_ORIGIN_ALLOW_ALL=True
REST_USE_JWT = True

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
#        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
#        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
        },
    },
    'root': {'level': 'INFO'},
}
from django.utils.translation import ugettext_lazy as _

LANGUAGES = [
    ('ru', _('Russian')),
    ('en', _('English')),
]

LANGUAGE_CODE = 'ru'
TIME_ZONE = 'EST'

USE_I18N = True
USE_L10N = True
USE_TZ = True

REST_SESSION_LOGIN = True
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_FILE_PATH = '/tmp/email-messages'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'dmitryro'
EMAIL_HOST_PASSWORD = 'nu45edi1'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
