# Generated by Django 2.0.4 on 2018-05-30 22:58

import custom.blogs.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tempblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField()),
                ('b_ip', models.CharField(blank=True, max_length=1250, null=True)),
                ('b_date', models.DateTimeField(blank=True, null=True)),
                ('uid', models.IntegerField()),
                ('b_subject', models.CharField(blank=True, max_length=1250, null=True)),
                ('b_message', models.CharField(blank=True, max_length=15250, null=True)),
                ('b_emotion', enumfields.fields.EnumField(enum=custom.blogs.models.BlogEmotion, max_length=1)),
                ('b_delete_mark', models.IntegerField()),
                ('b_marked_by', models.IntegerField()),
                ('last_edit_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
