# Generated by Django 2.0.4 on 2018-04-28 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=40, verbose_name='activation key')),
                ('user', models.OneToOneField(on_delete=None, related_name='api_registration_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
